[package]
name = "hyperoxide"
version = "0.1.0"
authors = ["axect <axect@outlook.kr>"]
edition = "2018"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
